Разметка
htmlacademy-adaptive/2318767-sedona-28 pull request #2
Opened 2023-04-14 15:26 UTC by RybkaA

2023-04-15 15:03 UTC, jumile requested changes
Антон, в целом хорошо, структура уже есть и в основном она правильная. Ошибка с разметкой по БЭМ только 1, я тебе написала в комментариях. 
Но! Есть ошибки в html-разметке - теги не там закрыты или не закрыты, или не те. Это, возможно, от спешки, поэтому обязательно проверяй на валидаторе.
Еще обрати внимание на пункт 2 в д/з. Файловая структура сайта должна быть точно, как там написано. HTML-страницы должны лежать в папке source.

И несколько уточнений/размышлений. Смотри, блок по БЭМ - это то, что будет использовано несколько раз. На одной странице или на разных - неважно. Следовательно, когда мы смотрим на макет, мы должны найти одинаковые части и подумать: а может, это один и тот же блок? 
Например, кусочки в преимуществах - ведь они одинаковые. А почему бы тогда не выделить их в блок? У нас, правда, несколько вариантов - с номерами, с фотографиями, с иконками. В принципе, каждый из вариантов может стать блоком. 
Другой кандидат на блок - фотография + информация  о ней в каталоге, я в комментариях написала.
А еще в Седоне совершенно одинаково выглядят кусочки заголовок+абзац в начале каждой страницы, и они тоже напрашиваются быть выделенными в блок.
Здесь решение за тобой, я лишь предлагаю варианты. Здесь важно, с одной стороны, без фанатизма, не намельчить, но если фрагменты страниц одинаковы на 90-100% - это точно повод для выделения их в блок.
В остальном все правильно. Жду форму. Кстати, там тоже есть немало одинаковых сущностей.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +      <div class="main-nav__wrapper">
Не факт, что эта обертка в будущем понадобится - надо будет это проконтролировать, чтобы она не оказалась лишней.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +      <img class="main-header__logo-image" src="#" width="#" height="#" alt="Логотип Sedona">
Размеры для изображения уже можно написать, а взять их надо из мобильной версии. Атрибут alt по критерия должен заканчивать точкой.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +  <section class="hero">
Этот блок "повис" между header и main, все-таки надо его к чему-то отнести.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +      <p class="iphoto__description-catalog">
Кажется, неверное название iphoto.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +    <img class="welcome" src="#" alt="Надпись Sedona на фоне гор">
Размеры для изображения не забудь указать, взять их нужно из мобильной версии. Также не хватает точки в alt.
Картинка точно должна быть самостоятельным блоком? Мне кажется, она сама по себе в таком виде нигде не переиспользуется, только в составе hero-блока.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +          <div class="photo__user description-photo">
А не лучше ли здесь использовать figure/figcaption для организации структуры фотогалереи?
И еще вопрос: описание фото ты выделил в блок. А может ли описание фото быть без фото? Логичнее сделать все вместе - как раз обернуть в figure и сделать его блоком.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +      <a class="copyright__link" href="#">
Посмотри адрес ссылки в техзадании, п.3.8.

2023-04-15 15:03 UTC, jumile commented on index.html
> +  <body class= "page-body">
Здесь предполагается отдельный блок или элемент блока page? Если второй вариант, то вместо дефиса должно быть двойное подчеркивание.
Кстати, в каталоге у этого тега вообще нет класса. Если уж мы решаем, что body - это блок или элемент блока, то так должно быть на всех страницах.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +        <li class="site-list__item site-list__item--active">
Это же каталог, так что эта ссылка уже не --active.
Вообще, текущую страницу у нас обозначает именно ссылка, а не пункт списка, и оформление, и модификатор текущей страницы лучше добавлять к тегу a.

2023-04-15 15:03 UTC, jumile commented on index.html
> +          <li class="advantages__item">
Открывающего ul не хватает. Пункты списка могут находиться только внутри списка.

2023-04-15 15:03 UTC, jumile commented on index.html
> +            <img src="#" width="#" height="#" alt="Мост дьявола">
Картинку ведь будем стилизовать, давай сразу обозначим ее место в иерархии БЭМ.

2023-04-15 15:03 UTC, jumile commented on index.html
> +        <div class="interested__wrapper">
Эта обертка пока представляется лишней. Можно не удалять, но в будущем проконтролировать, действительно ли она нужна.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +</body>
Не хватает закрывающего html.

2023-04-15 15:03 UTC, jumile commented on index.html
> +</html>
Не хватает закрывающего body.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +    <section class="photo__wrapper">
Здесь нельзя использовать photo__wrapper, потому что этот тег находится отдельно от того, к которому применен класс photo, т.е. отдельно от блока photo. Элементами блока могут быть только те теги, которые находятся внутри него. А этот тег в section.photo не вложен, следовательно, ни он, ни все остальные его потомки элементами блока photo быть не могут.
Соглашусь, если ты решишь, что это самостоятельный блок и придумаешь ему другое название.

2023-04-15 15:03 UTC, jumile commented on index.html
> +    <section class="hero">
Здесь те же вопросы, что и в каталоге - блок висит между header и main, а картинка внутри него претендует на отдельный блок, но вот оправданно ли?

2023-04-15 15:03 UTC, jumile commented on index.html
> +  </body>
Этот тег точно не на своем месте.

2023-04-15 15:03 UTC, jumile commented on index.html
> +    <div class="main-footer__wrapper">
Вот этот тег открыт, но не закрыт.
Вообще, эта обертка может оказаться лишней, по крайней мере, пока в ней нет необходимости.

2023-04-15 15:03 UTC, jumile commented on catalog.html
> +  <footer class="catalog-footer">
Мне кажется нерациональным выделять в разные блоки футер на двух страницах. Он же одинаковый, значит, это один и тот же блок, нет смысла разделять его на main-footer и catalog-footer.. 
В этом смысле с хедером ты сделал правильно - один и тот же блок переиспользован на 2 страницах сайта. С футером надо сделать так же.

2023-04-17 10:54 UTC, RybkaA commented on catalog.html
> +      <div class="main-nav__wrapper">
У меня имеются идеи по ней, на контроль поставлю

2023-04-17 10:54 UTC, RybkaA commented on catalog.html
> +      <img class="main-header__logo-image" src="#" width="#" height="#" alt="Логотип Sedona">
+

2023-04-17 17:44 UTC, jumile requested changes
Антон, ты молодец, разметка почти готова. Мне понравилось, как ты сделал form.html - очень аккуратная, правильная верстка, ничего не пропущено. Главную страницу тоже практически "довел до ума". Для copyright в футере посмотри адрес ссылки в техзадании, п.3.8. Ссылка должна вести НЕ на главную страницу сайта Академии))
Больше всего путаницы в каталоге - там есть элементы без блоков, частично это связано с опечатками, но надо навести там порядок и сделать так же хорошо, как форму.

2023-04-17 17:44 UTC, jumile commented on source/catalog.html
> +      <img class="welcome__sedona-image" src="#" alt="Надпись Sedona на фоне гор.">
welcome__sedona-image - получается, это элемент блока welcome. Но такого блока нет. Думаю, здесь будет правильно отнести это изображение к блоку hero, т.е. hero__sedona-image.

2023-04-17 17:44 UTC, jumile commented on source/catalog.html
> +        </figure>
Попробуем разобраться с этими сущностями (комментарий относится ко всему section с фотографиями).
Итак, у тебя есть section.photo - это блок. У него есть элементы h1.photo__title-catalog и p.photo__description-catalog - это верно. Также у него есть элемент div.photo__wrapper - видимо, обертка для галереи, тоже ОК. 
А вот потом идет figure.gallery__item.photo - во-первых, это элемент блока gallery - а где же сам блок? Тут ошибка. Если мы делаем figure элементом, у нас 2 варианта: 1) это элемент section.photo, тогда будет что-то типа photo__item 2) это элемент обертки, которую ты сделал для галереи - тогда обертку нужно сделать еще и блоком, т.к. сейчас она только элемент и фигуру к ней никак не привяжешь. 
Тег figure также является блоком photo - тут я поддерживаю твое решение, но вот название для блока напрягает, ведь photo - это уже section. Теоретически так можно, но ты уверен, что у section и figure будут одинаковые стили? Мне кажется, вряд ли.
Смотрим дальше. Внутри фигуры у нас элементы а.photo__link, img.photo__image - да, это элементы фигуры. По идее, figcaption тоже сюда должен относиться, но он оказался сам по себе элементом не заданного блока description (description__photo). Дальше структура была бы верная, если бы был блок description-photo: элементы р.description-photo__title, р.description-photo__author, р.description-photo__like (Кстати, в первом варианте работы здесь было написано правильно: description-photo).
Как тут поправить? Во-первых, подпись - неотъемлемая часть фигуры, она точно должна быть ее элементом. Выделять ли подпись в блок? Да, можно, тогда поправляем ему название на description-photo, чтобы элементы внутри не висели сами по себе.

2023-04-17 17:44 UTC, jumile commented on source/index.html
> +            <a class="site-list__link site-list__link-active" href="index.html">
site-list__link-active - двойной дефис нужен для модификатора: site-list__link--active

2023-04-17 17:44 UTC, jumile commented on source/catalog.html
> +            <a class="site-list__link site-list__link-active" href="catalog.html">
Для модификатора используем двойной дефис: site-list__link--active

2023-04-17 17:44 UTC, jumile commented on source/index.html
> +      <img class="welcome" src="#" alt="Welcome To the Gorgeous Sedona Because the Grand Canyon Sucks!">
Вряд ли это изображение надо выделять в отд. блок. Скорее, нужно сделать элементом блока hero.

2023-04-17 17:44 UTC, jumile commented on source/index.html
> +        <a class="interested-button button" href="#">
interested-button button - получается 2 блока, но подозреваю, что первый класс имел в виду элемент interested__button.

2023-04-17 17:44 UTC, jumile commented on source/form.html
> +  <title>Седона форма</title>
Здесь лучше написать Отзыв о Седоне или что-то подобное - это же название для посетителя, важно показать ему суть страницы, а не техническую сторону.

2023-04-17 17:44 UTC, jumile commented on source/form.html
> +            <a class="site-list__link site-list__link-active" href="form.html">
В модификаторе должно быть 2 дефиса.

2023-04-17 17:44 UTC, jumile commented on source/form.html
> +      <img class="welcome__sedona-image" src="#" alt="Надпись Sedona на фоне гор.">
Картинка является элементом несуществующего блока welcome. Думаю, надо переделать на hero.

2023-04-17 17:44 UTC, jumile commented on source/form.html
> +      <form class="feedback__form" action="https://echo.htmlacademy.ru/" method="POST">
Форму имеет смысл  выделить в блок, эта часть сайта точно может быть переиспользована.

2023-04-17 17:44 UTC, jumile commented on source/form.html
> +        <fieldset class="feedback__field-group">
И тогда филдсеты и все остальное будут элементами формы, а не section.

2023-04-17 17:44 UTC, jumile commented on source/form.html
> +                <span class="control-label">Скорее положительное</span>
control-input, control-mark, control-label - это блоки? А они могут быть переиспользованы по отдельности? Или все-таки они элементы блока control? Тогда пишем их через нижнее подчеркивание, и это будет правильно.

2023-04-18 09:41 UTC, jumile approved these changes
Да, теперь все отлично.

2023-04-18 09:41 UTC, merged